import BlogShell from './blog-shell';

export const metadata = {
  title: 'Pool Service Software Blog | PoolBossPro',
  description: 'Guides on pool service scheduling, route management, water-chemistry tracking, cleaning, maintenance, invoicing, and running a pool business with software.',
};

const silo0 = [
  { title: 'How Pool Service Software Charges Card-on-File for Recurring Pool Cleanings', description: 'See how pool service software stores a card on file and auto-charges every recurring pool cleaning, so weekly routes get paid the same day without chasing invoices.', href: '/blogs/pool-service-software-card-on-file-payments' },
  { title: 'Tracking Chemical Costs Per Pool With Pool Service Software', description: 'How pool service software tracks chlorine, acid, and shock costs per pool so you know the true margin on every weekly cleaning stop and account.', href: '/blogs/pool-service-software-chemical-cost-tracking' },
  { title: 'How Pool Service Software Calculates Chemical Dosages From Water Readings', description: 'How pool service software turns chlorine, pH, and alkalinity readings into exact chemical dosages using pool volume, so every tech doses water correctly.', href: '/blogs/pool-service-software-chemical-dosage-calculations' },
  { title: 'Managing Commercial Pool Accounts With Pool Service Software', description: 'How pool service software manages commercial pool accounts: multi-pool profiles, recurring routes, water chemistry logs, dispatch, and combined invoicing.', href: '/blogs/pool-service-software-commercial-pool-accounts' },
  { title: 'How Pool Service Software Handles Crew Dispatch and Daily Routing', description: 'How pool service software builds route-based weekly schedules, dispatches crews with pool profiles and chemistry forms, and tracks completion in real time.', href: '/blogs/pool-service-software-crew-dispatch-daily-routing' },
  { title: 'How Pool Service Software Improves Retention With Complete Service History', description: 'How a complete service history in pool service software keeps weekly cleaning customers from canceling by proving every visit, reading, and dose was done.', href: '/blogs/pool-service-software-customer-retention-service-history' },
  { title: 'Sending Automatic Customer Texts From Your Pool Service Software', description: 'How automatic customer texts in pool service software fire at every touchpoint — dispatch, completion with water chemistry, payment issues — with zero manual effort.', href: '/blogs/pool-service-software-customer-text-updates' },
  { title: 'Tracking Cyanuric Acid, Salt, and Phosphate Levels in Pool Service Software', description: 'See how PoolBossPro logs cyanuric acid, salt, and phosphate readings per pool so techs balance water faster and keep a clean chemistry history.', href: '/blogs/pool-service-software-cyanuric-salt-phosphate-tracking' },
  { title: 'How Pool Service Software Generates End-of-Day Service Reports for Customers', description: 'See how pool service software turns each weekly stop into an automatic end-of-day service report with chemistry readings, photos, and a clear summary for customers.', href: '/blogs/pool-service-software-end-of-day-service-reports' },
  { title: 'How Pool Service Software Turns Equipment Repairs Into Trackable Work Orders', description: 'See how pool service software turns pump, filter, and heater repairs into trackable work orders tied to the pool profile, the crew, the invoice, and the customer.', href: '/blogs/pool-service-software-equipment-repair-work-orders' },
  { title: 'Setting Up Pool Service Software in Your First Week: A Practical Guide', description: 'A practical first-week setup plan for pool service software: import customers, build pool profiles, set recurring routes, and turn on chemistry logging and invoicing.', href: '/blogs/pool-service-software-first-week-setup-guide' },
  { title: 'Managing Green-to-Clean Recovery Jobs With Pool Service Software', description: 'How pool service software schedules multi-visit green-to-clean recovery jobs, logs water chemistry each pass, and bills the labor and chemicals automatically.', href: '/blogs/pool-service-software-green-to-clean-recovery-jobs' },
  { title: 'Importing Your Existing Pool Accounts Into Pool Service Software', description: 'Move your existing pool cleaning accounts into PoolBossPro fast: pool profiles, recurring routes, water chemistry history, and card-on-file payments without losing data.', href: '/blogs/pool-service-software-importing-existing-pool-accounts' },
  { title: 'Using the Job Board in Pool Service Software to Catch Overflow and One-Off Pool Jobs', description: 'How the Job Board in pool service software captures green-to-clean, repairs, and one-off pool jobs so nothing falls through the cracks.', href: '/blogs/pool-service-software-job-board-overflow-work' },
  { title: 'Pool Service Software vs Paper Route Sheets: A Side-by-Side Comparison', description: 'See how pool service software beats paper route sheets for recurring scheduling, water chemistry logging, dispatch, invoicing, and customer texts.', href: '/blogs/pool-service-software-manual-vs-software-comparison' },
  { title: 'Preventing Missed Pool Stops With Pool Service Software Verification', description: 'How pool service software verifies every weekly stop is serviced with route tracking, chemistry logs, completion status, and customer texts so no pool gets skipped.', href: '/blogs/pool-service-software-missed-stop-prevention' },
  { title: 'Capturing Photo Proof of Service in Pool Service Software', description: 'How photo proof of service in pool service software documents every cleaning, cuts disputes, and reassures customers their pool was actually serviced.', href: '/blogs/pool-service-software-photo-proof-of-service' },
  { title: 'Scheduling Pool Openings and Closings With Pool Service Software', description: 'How pool service software schedules seasonal pool openings and closings, dispatches crews, logs water chemistry, and invoices with card on file automatically.', href: '/blogs/pool-service-software-pool-openings-closings' },
  { title: 'Pool and Property Profiles: How Pool Service Software Stores Pool Type, Gallons, and Equipment', description: 'See how PoolBossPro pool service software stores pool type, gallons, and equipment in property profiles so every tech shows up knowing the pool.', href: '/blogs/pool-service-software-pool-property-profiles' },
  { title: 'Recurring Invoicing and Autopay in Pool Service Software', description: 'How PoolBossPro automates recurring invoicing and card-on-file autopay so weekly pool cleaning revenue lands on time without chasing checks.', href: '/blogs/pool-service-software-recurring-invoicing-autopay' },
  { title: 'Replacing Spreadsheets and Group Texts With Pool Service Software', description: 'How pool service software replaces the spreadsheets, sticky notes, and group texts that pool route businesses outgrow, with one system for scheduling, chemistry, and billing.', href: '/blogs/pool-service-software-replacing-spreadsheets-and-texts' },
  { title: 'Reading Revenue and Route Reports in Pool Service Software', description: 'How to read revenue and route reports in pool service software to spot dead routes, slow payers, missed chemistry visits, and where your pool business actually earns.', href: '/blogs/pool-service-software-revenue-and-route-reporting' },
  { title: 'The ROI of Pool Service Software for a Small Pool Cleaning Operation', description: 'See how pool service software pays for itself through tighter routes, faster invoicing, card-on-file payments, and water chemistry logs that protect your accounts.', href: '/blogs/pool-service-software-roi-for-small-operators' },
  { title: 'How Pool Service Software Builds Route-Based Recurring Schedules for Weekly Cleanings', description: 'How pool service software auto-builds route-based recurring schedules for weekly cleanings, balancing crew routes, water chemistry, and customer texts.', href: '/blogs/pool-service-software-route-based-recurring-scheduling' },
  { title: 'How Pool Service Software Improves Route Density and Profit Per Stop', description: 'How pool service software tightens recurring weekly routes, packs stops by geography, and raises profit per stop with chemistry logging, invoicing, and reporting.', href: '/blogs/pool-service-software-route-density-profit-per-stop' },
  { title: 'How Pool Service Software Helps You Scale From One Tech to Five Crews', description: 'See how pool service software handles recurring routes, dispatch, water chemistry logs, and card-on-file billing so you can scale from one tech to five crews.', href: '/blogs/pool-service-software-scaling-from-one-to-five-crews' },
  { title: 'How Pool Service Software Rebalances Routes Between Busy and Slow Seasons', description: 'See how PoolBossPro rebalances pool service routes between peak and slow seasons with recurring scheduling, smart dispatch, and route revenue reporting.', href: '/blogs/pool-service-software-seasonal-route-rebalancing' },
  { title: 'Mobile Service Checklists in Pool Service Software for Pool Techs', description: 'How mobile service checklists in pool service software guide pool techs through every weekly stop, capture water chemistry, and prove the work was done.', href: '/blogs/pool-service-software-tech-mobile-checklists' },
  { title: 'Using Pool Service Software to Upsell Filter Cleans and Equipment Work', description: 'See how pool service software surfaces filter cleans and equipment upsells from chemistry trends, pool profiles, and the Job Board &mdash; then bills them on file.', href: '/blogs/pool-service-software-upsell-filter-and-equipment-work' },
  { title: 'Logging Chlorine, pH, and Alkalinity Readings in Pool Service Software', description: 'How pool service software logs chlorine, pH, and alkalinity readings on every stop, ties them to the pool profile, and turns water chemistry into a record.', href: '/blogs/pool-service-software-water-chemistry-readings-log' },
];

const silo1 = [
  { title: 'Automated Customer Texts From Your Pool Scheduling Software', description: 'How PoolBossPro fires automated customer texts off your recurring pool routes &mdash; reminders, on-the-way alerts, water-reading summaries, and payment receipts.', href: '/blogs/automated-customer-texts-from-your-pool-scheduling-software' },
  { title: 'Balancing Technician Workloads Across Pool Routes With Software', description: 'How pool scheduling software balances tech workloads across routes by stop count, drive time, and pool complexity so no crew is overloaded and none runs light.', href: '/blogs/balancing-tech-workloads-across-pool-routes-with-software' },
  { title: 'Choosing Pool Scheduling Software: A Feature Checklist for Pool Service Owners', description: 'A practical feature checklist for pool service owners evaluating pool scheduling software, from recurring route scheduling and dispatch to water chemistry logging and billing.', href: '/blogs/choosing-pool-scheduling-software-a-feature-checklist' },
  { title: 'Crew Dispatch and Routing Made Simple With Pool Scheduling Software', description: 'How pool scheduling software dispatches route-based pool cleaning stops, water chemistry forms, and pool profiles to techs without a single morning phone call.', href: '/blogs/crew-dispatch-and-routing-with-pool-scheduling-software' },
  { title: 'Customer Experience Wins From Reliable Pool Scheduling Software', description: 'See how reliable pool scheduling software wins customer loyalty with on-time recurring stops, water chemistry proof, texts, and card-on-file billing.', href: '/blogs/customer-experience-wins-from-reliable-pool-scheduling-software' },
  { title: 'Giving Pool Techs Their Daily Route on a Phone With Scheduling Software', description: 'How PoolBossPro puts each pool tech&apos;s daily route, water-chemistry logging, and invoicing on their phone so crews run stops without printouts or calls.', href: '/blogs/giving-pool-techs-their-daily-route-on-a-phone' },
  { title: 'Handling Skips, Reschedules, and Rain Days in Pool Scheduling Software', description: 'How PoolBossPro handles skips, reschedules, and rain days on recurring pool routes without breaking your weekly cleaning cadence or billing.', href: '/blogs/handling-skips-reschedules-and-rain-days-in-pool-scheduling-software' },
  { title: 'How Pool Scheduling Software Builds Tighter Route Density and Cuts Drive Time', description: 'See how pool scheduling software clusters weekly cleaning stops, tightens route density, and cuts drive time so techs service more pools per day.', href: '/blogs/how-pool-scheduling-software-builds-tighter-route-density' },
  { title: 'How Pool Scheduling Software Prevents Missed Weekly Pool Cleanings', description: 'How PoolBossPro recurring route scheduling, the Job Board, and crew dispatch make sure every weekly pool cleaning gets serviced &mdash; no skipped stops, no lost accounts.', href: '/blogs/how-pool-scheduling-software-prevents-missed-pool-cleanings' },
  { title: 'Invoicing the Moment a Pool Stop Is Completed With Scheduling Software', description: 'See how pool scheduling software invoices each pool stop the second a tech taps complete and charges the card on file, so your route collects itself the same day.', href: '/blogs/invoicing-the-moment-a-pool-stop-is-completed' },
  { title: 'Logging Water Chemistry on Every Scheduled Pool Stop With Your Software', description: 'Log chlorine, pH, alkalinity, cyanuric, salt, and phosphate on every scheduled pool stop with PoolBossPro so your route data stays accurate and proven.', href: '/blogs/logging-water-chemistry-on-every-scheduled-pool-stop' },
  { title: 'Managing Pool Openings and Closings With Pool Scheduling Software', description: 'See how PoolBossPro pool scheduling software helps you batch, route, and bill seasonal pool openings and closings so nothing falls through the cracks.', href: '/blogs/managing-pool-openings-and-closings-with-scheduling-software' },
  { title: 'Manual Scheduling vs Pool Scheduling Software: The Real Cost to Your Pool Business', description: 'See the real cost of running pool routes on paper and texts vs PoolBossPro scheduling software that automates recurring routes, dispatch, and invoicing.', href: '/blogs/manual-scheduling-vs-pool-scheduling-software-the-real-cost' },
  { title: 'Onboarding New Pool Customers Into Your Scheduling Software', description: 'How PoolBossPro turns a new pool account into a complete property profile, recurring route slot, and billable card-on-file customer in minutes.', href: '/blogs/onboarding-new-pool-customers-into-your-scheduling-software' },
  { title: 'Pool and Property Profiles That Power Smarter Scheduling', description: 'How detailed pool and property profiles in PoolBossPro drive smarter recurring scheduling, accurate routing, faster water chemistry logging, and correct invoicing.', href: '/blogs/pool-and-property-profiles-that-power-smarter-scheduling' },
  { title: 'Pool Scheduling Software: The Complete Guide for Pool Service Businesses', description: 'How pool scheduling software handles recurring weekly routes, crew dispatch, water chemistry logging, card-on-file billing, and customer texts for pool pros.', href: '/blogs/pool-scheduling-software-complete-guide' },
  { title: 'Recurring Billing and Card-on-File Payments Tied to the Pool Schedule', description: 'How PoolBossPro charges the card on file the moment a weekly pool cleaning is logged complete, so billing matches the route and AR disappears.', href: '/blogs/recurring-billing-and-card-on-file-tied-to-the-pool-schedule' },
  { title: 'Reducing Windshield Time With Pool Route Scheduling Software', description: 'How PoolBossPro pool route scheduling software clusters and sequences recurring pool stops to cut windshield time, lower fuel costs, and fit more pools per day.', href: '/blogs/reducing-windshield-time-with-pool-route-scheduling-software' },
  { title: 'Reporting and Dashboards Built on Your Pool Schedule Data', description: 'How PoolBossPro turns your recurring pool schedule, chemistry logs, and payments into live dashboards and reports that show route revenue, completion, and overdue accounts.', href: '/blogs/reporting-and-dashboards-built-on-your-pool-schedule-data' },
  { title: 'Route-Based Scheduling vs Appointment Scheduling: What Pool Service Software Gets Right', description: 'Why pool service software uses route-based recurring scheduling instead of appointment booking, and how that keeps weekly cleaning routes tight and profitable.', href: '/blogs/route-based-scheduling-vs-appointment-scheduling-for-pool-service' },
  { title: 'Scaling From One Crew to Many With Pool Scheduling Software', description: 'How pool scheduling software lets a one-crew pool service grow to many crews with recurring routes, dispatch, water chemistry logs, and card-on-file billing.', href: '/blogs/scaling-from-one-crew-to-many-with-pool-scheduling-software' },
  { title: 'Scheduling Equipment Repair Visits Alongside Recurring Pool Routes', description: 'How PoolBossPro slots equipment repair visits into your recurring weekly pool routes using the Job Board, smart dispatch, and route-aware scheduling.', href: '/blogs/scheduling-equipment-repair-visits-alongside-recurring-pool-routes' },
  { title: 'Scheduling Green-to-Clean Pool Recovery Jobs With Pool Scheduling Software', description: 'Schedule, route, and track multi-visit green-to-clean pool recovery jobs with water chemistry logging, dispatch, and card-on-file invoicing in PoolBossPro.', href: '/blogs/scheduling-green-to-clean-pool-recovery-jobs-with-software' },
  { title: 'Pool Scheduling Software That Keeps Service History in One Place', description: 'PoolBossPro ties recurring pool route scheduling to a complete per-pool service history so every visit, chemistry reading, and repair lives in one record.', href: '/blogs/scheduling-software-that-keeps-pool-service-history-in-one-place' },
  { title: 'Seasonal Scheduling for Pool Service: Ramping Up and Down With Software', description: 'See how PoolBossPro handles seasonal pool service scheduling &mdash; ramping recurring routes up in spring, scaling down in fall, and dispatching openings and closings.', href: '/blogs/seasonal-scheduling-for-pool-service-with-software' },
  { title: 'How to Set Up Recurring Weekly Pool Routes in Pool Scheduling Software', description: 'Set up recurring weekly pool routes in PoolBossPro so every cleaning auto-schedules, dispatches to the right tech, and keeps your route tight all season.', href: '/blogs/setting-up-recurring-weekly-pool-routes-in-scheduling-software' },
  { title: 'The ROI of Pool Scheduling Software for a Pool Route Business', description: 'See how pool scheduling software pays for itself by tightening routes, automating recurring weekly stops, and turning every visit into a billable, paid invoice.', href: '/blogs/the-roi-of-pool-scheduling-software-for-a-pool-route-business' },
  { title: 'Tracking Chlorine, pH, and Alkalinity Trends by Scheduled Pool', description: 'See how PoolBossPro logs chlorine, pH, and alkalinity at every scheduled pool stop and turns those readings into trend lines you can act on.', href: '/blogs/tracking-chlorine-ph-and-alkalinity-trends-by-scheduled-pool' },
  { title: 'Turning One-Off Pool Jobs Into Recurring Scheduled Revenue', description: 'Turn one-off green-to-clean and repair jobs into recurring weekly pool routes with scheduling software that locks in cadence, card-on-file billing, and chemistry logs.', href: '/blogs/turning-one-off-pool-jobs-into-recurring-scheduled-revenue' },
  { title: 'Using the Job Board to Fill Open Pool Service Stops Fast', description: 'See how PoolBossPro&apos;s Job Board fills open pool service stops fast &mdash; reassigning skipped cleanings, green-to-cleans, and repairs to the right crew.', href: '/blogs/using-the-job-board-to-fill-open-pool-service-stops' },
];

const silo2 = [
  { title: 'Building Pool and Property Profiles That Make Every Visit Faster', description: 'See how PoolBossPro pool and property profiles store pool type, gallons, equipment, gate codes, and chemistry history so every cleaning visit runs faster.', href: '/blogs/pool-cleaning-software-building-property-profiles' },
  { title: 'Getting Your Pool Service Ready for Peak Season With Software', description: 'How PoolBossPro gets your pool service ready for peak season: clean route data, recurring schedules, card-on-file billing, and chemistry logging dialed in.', href: '/blogs/pool-cleaning-software-busy-season-readiness' },
  { title: 'Card-on-File Billing That Runs Your Recurring Pool Charges Automatically', description: 'Charge stored cards automatically after every completed pool visit. PoolBossPro removes invoicing, collections, and end-of-month billing for recurring pool routes.', href: '/blogs/pool-cleaning-software-card-on-file-billing' },
  { title: 'Logging Chlorine, pH, and Alkalinity in the Field With Pool Cleaning Software', description: 'How pool cleaning software lets techs log chlorine, pH, and alkalinity right at the pool, tie readings to the property profile, and build a usable water history.', href: '/blogs/pool-cleaning-software-chlorine-ph-alkalinity-logging' },
  { title: 'The Real Cost of Missed Pool Visits and How Software Prevents Them', description: 'Missed pool visits cost real money in green-to-clean recoveries, refunds, and lost accounts. See how pool cleaning software prevents them with verified stops.', href: '/blogs/pool-cleaning-software-cost-of-missed-visits' },
  { title: 'Customer Text Updates That Cut Down on Where-Is-My-Tech Calls', description: 'PoolBossPro auto-texts pool clients on-my-way, arrival, and after-service updates so techs stop fielding where-is-my-tech calls and stay on route.', href: '/blogs/pool-cleaning-software-customer-text-updates' },
  { title: 'Tracking Cyanuric Acid, Salt, and Phosphate Readings Over Time', description: 'See how PoolBossPro logs cyanuric acid, salt, and phosphate per pool and charts the trend so techs balance water faster and catch problems early.', href: '/blogs/pool-cleaning-software-cyanuric-salt-phosphate-tracking' },
  { title: 'Handling Same-Day Dispatch Changes When a Tech Calls Out', description: 'How pool cleaning software lets you reassign a sick tech&apos;s route in minutes &mdash; dispatching full pool profiles and chemistry forms to the covering crew.', href: '/blogs/pool-cleaning-software-dispatch-day-of-changes' },
  { title: 'Closing Out the Day in Minutes Instead of Evenings of Paperwork', description: 'PoolBossPro auto-closes your pool route each evening&mdash;logging chemistry, invoicing card-on-file, and texting customers&mdash;so closeout takes minutes, not hours.', href: '/blogs/pool-cleaning-software-end-of-day-closeout' },
  { title: 'Turning Equipment Repairs Into Tracked Work Orders, Not Sticky Notes', description: 'How PoolBossPro turns pool equipment repairs into tracked work orders tied to the pool profile, so nothing gets lost between the route stop and the invoice.', href: '/blogs/pool-cleaning-software-equipment-repair-work-orders' },
  { title: 'Your First Week on Pool Cleaning Software: A Setup Roadmap', description: 'A day-by-day roadmap for your first week on pool cleaning software: load profiles, build recurring routes, turn on chemistry logging, invoicing, and texts.', href: '/blogs/pool-cleaning-software-getting-started-first-week' },
  { title: 'Managing Green-to-Clean Recovery Jobs Inside Pool Cleaning Software', description: 'How pool cleaning software runs multi-visit green-to-clean recovery jobs, logs water chemistry on every pass, and bills all the chlorine and labor automatically.', href: '/blogs/pool-cleaning-software-green-to-clean-jobs' },
  { title: 'Hiring Your First Pool Tech? How the Software Makes Onboarding Easy', description: 'PoolBossPro turns a new pool tech into a productive route runner fast with built routes, dispatch, pool profiles, water chemistry logging, and card-on-file billing.', href: '/blogs/pool-cleaning-software-hiring-first-tech' },
  { title: 'Moving Your Customer List Into Pool Cleaning Software Without Losing Data', description: 'How to import your pool service customer list into PoolBossPro cleanly, keeping addresses, pool profiles, water chemistry history, and billing intact.', href: '/blogs/pool-cleaning-software-import-customer-list' },
  { title: 'How the Job Board Keeps Every Pool Visit From Slipping Through', description: 'See how the PoolBossPro Job Board catches overflow pool visits, callbacks, and green-to-clean jobs so nothing falls off your recurring cleaning schedule.', href: '/blogs/pool-cleaning-software-job-board-walkthrough' },
  { title: 'Paper Logs vs Pool Cleaning Software: An Honest Comparison', description: 'An honest look at paper service logs vs PoolBossPro pool cleaning software for routes, water chemistry, invoicing, and customer texts.', href: '/blogs/pool-cleaning-software-manual-vs-software-comparison' },
  { title: 'One Login vs Five Apps: Why Pool Companies Consolidate', description: 'Pool companies running five apps for scheduling, routing, chemistry logs, invoicing, and texts pay for double entry. See why one login wins.', href: '/blogs/pool-cleaning-software-one-login-vs-five-apps' },
  { title: 'Getting the Owner Out of the Truck With Pool Cleaning Software', description: 'How PoolBossPro lets a pool service owner step out of the truck by running recurring routes, dispatch, chemistry logging, and billing without you on every stop.', href: '/blogs/pool-cleaning-software-owner-out-of-the-truck' },
  { title: 'Scheduling Pool Openings and Closings Without the Spring Scramble', description: 'Use PoolBossPro to batch, route, and dispatch pool opening and closing jobs so the busy seasons run on a plan instead of a frantic scramble.', href: '/blogs/pool-cleaning-software-pool-opening-closing-jobs' },
  { title: 'Setting Up Recurring Weekly Pool Visits That Build Themselves', description: 'How PoolBossPro builds your recurring weekly pool routes automatically, so every cleaning, water test, and invoice queues itself without manual scheduling.', href: '/blogs/pool-cleaning-software-recurring-weekly-visits' },
  { title: 'Keeping Pool Customers Longer With Consistent, Documented Service', description: 'How pool cleaning software cuts customer churn with consistent route-based visits, logged water chemistry, photo proof, and automatic billing on every stop.', href: '/blogs/pool-cleaning-software-reducing-customer-churn' },
  { title: 'Reports That Tell You Which Pools and Routes Actually Make Money', description: 'See how PoolBossPro reporting reveals which pools, routes, and crews are profitable so you can reprice, reroute, and grow your pool service business.', href: '/blogs/pool-cleaning-software-reporting-that-drives-decisions' },
  { title: 'The ROI of Pool Cleaning Software for a Small Pool Company', description: 'The real return on pool cleaning software: time saved on routing, recovered weekly cleanings, faster card-on-file payments, and tighter water chemistry records.', href: '/blogs/pool-cleaning-software-roi-for-small-pool-companies' },
  { title: 'Adding a Second Crew and a Second Route the Smart Way', description: 'How pool cleaning software lets you split a full route into two crews, balance stops, and dispatch both without losing chemistry logs or billing.', href: '/blogs/pool-cleaning-software-second-crew-second-route' },
  { title: 'Proof of Service: Photo Documentation Customers Actually Trust', description: 'How photo proof of service in pool cleaning software builds customer trust, ends route disputes, and proves every weekly visit was actually done right.', href: '/blogs/pool-cleaning-software-service-proof-photos' },
  { title: 'When Your Spreadsheet Breaks: Signs You Have Outgrown It', description: 'Spreadsheets cannot run recurring pool routes, log water chemistry, or invoice clients. Here are the signs your pool service has outgrown the grid.', href: '/blogs/pool-cleaning-software-spreadsheet-breaking-point' },
  { title: 'Stop Chasing Checks: Faster Payments With Pool Cleaning Software', description: 'See how pool cleaning software invoices each recurring stop the day it&apos;s serviced and collects by card, so you stop chasing checks and get paid faster.', href: '/blogs/pool-cleaning-software-stop-chasing-checks' },
  { title: 'Tighter Routes, More Pools Per Day: Route Density With the Software', description: 'How pool cleaning software builds dense recurring routes, packs stops by geography, and cleans more pools per day with dispatch, chemistry logging, and invoicing.', href: '/blogs/pool-cleaning-software-tighter-routes-more-pools' },
  { title: 'Turning Water Readings Into Repair and Upsell Opportunities', description: 'How PoolBossPro turns logged chlorine, pH, and salt readings into flagged repairs, upsells, and invoiced work your pool crew would otherwise miss.', href: '/blogs/pool-cleaning-software-upsell-repairs-from-readings' },
  { title: 'Spotting Water Chemistry Trends Pool Cleaning Software Catches for You', description: 'How pool cleaning software turns weekly chlorine, pH, alkalinity, and cyanuric readings into trends that flag drifting pools before they turn green.', href: '/blogs/pool-cleaning-software-water-chemistry-trends' },
];

const silo3 = [
  { title: 'How Pool Chemical Tracking Software Logs Chlorine, pH, and Alkalinity in the Field', description: 'See how pool chemical tracking software lets techs log chlorine, pH, and alkalinity at the pool, tie readings to the property, and dose right.', href: '/blogs/how-pool-chemical-tracking-software-logs-water-chemistry' },
  { title: 'Card-on-File Payments and Chemical Billing in Pool Chemical Tracking Software', description: 'How pool chemical tracking software charges cards on file the day each cleaning is done and bills chemical usage straight from the water test log.', href: '/blogs/pool-chemical-tracking-software-card-on-file-payments' },
  { title: 'How Pool Chemical Tracking Software Ties Readings to Chemical Inventory', description: 'See how PoolBossPro links water chemistry readings to chemical inventory so every dose drawn down on a pool route shows up in your stock and reports.', href: '/blogs/pool-chemical-tracking-software-chemical-inventory' },
  { title: 'Reading a Pool\'s Chemistry History and Trends in Your Tracking Software', description: 'See how PoolBossPro turns weekly chlorine, pH, and alkalinity readings into chemistry history and trends that help you fix problem pools fast.', href: '/blogs/pool-chemical-tracking-software-chemistry-history-trends' },
  { title: 'Pool Chemical Tracking Software for Commercial Pool Logs and Records', description: 'PoolBossPro logs chlorine, pH, and alkalinity per visit so commercial pool service crews keep clean, time-stamped chemical records on every account.', href: '/blogs/pool-chemical-tracking-software-commercial-pool-compliance' },
  { title: 'Pool Chemical Tracking Software: The Complete Guide for Pool Service Businesses', description: 'How pool chemical tracking software logs chlorine, pH, alkalinity, cyanuric, salt, and phosphate per pool so your crews dose right and bill faster.', href: '/blogs/pool-chemical-tracking-software-complete-guide' },
  { title: 'Pool Chemical Tracking Software for Crew Dispatch and Route Density', description: 'See how PoolBossPro ties water chemistry logging to crew dispatch and route density so every pool gets serviced in the tightest, most profitable order.', href: '/blogs/pool-chemical-tracking-software-crew-dispatch-routing' },
  { title: 'Sending Customers Water Chemistry Reports by Text From Your Software', description: 'How PoolBossPro texts customers a clean water chemistry report after every pool visit so they see chlorine, pH, and balance proof without a phone call.', href: '/blogs/pool-chemical-tracking-software-customer-text-reports' },
  { title: 'Building Customer Trust With Transparent Chemical Tracking Software', description: 'See how PoolBossPro chemical tracking software shares every chlorine, pH, and alkalinity reading with customers to build trust and justify your monthly rate.', href: '/blogs/pool-chemical-tracking-software-customer-transparency' },
  { title: 'Managing Cyanuric Acid With Pool Chemical Tracking Software', description: 'See how PoolBossPro logs cyanuric acid by pool, flags creep over 100 ppm, and tells techs when to drain and dilute on the weekly route.', href: '/blogs/pool-chemical-tracking-software-cyanuric-acid-management' },
  { title: 'A Pool Tech\'s Daily Workflow in Pool Chemical Tracking Software', description: 'Walk through a pool tech\'s full day in PoolBossPro&mdash;from morning dispatch to water chemistry logging, photos, billing, and the end-of-day closeout.', href: '/blogs/pool-chemical-tracking-software-daily-tech-workflow' },
  { title: 'How Pool Chemical Tracking Software Calculates Dosing by Pool Gallons', description: 'See how PoolBossPro uses the pool gallon count on each property profile to calculate exact chlorine, acid, and stabilizer doses for every stop.', href: '/blogs/pool-chemical-tracking-software-dosing-by-gallons' },
  { title: 'Turning Chemical Readings Into Equipment Repair Revenue With Software', description: 'See how PoolBossPro turns chlorine, pH, and salt readings into flagged equipment repair leads, quotes, and invoices on every weekly pool route.', href: '/blogs/pool-chemical-tracking-software-equipment-repair-leads' },
  { title: 'Using Pool Chemical Tracking Software to Run Green-to-Clean Recoveries', description: 'How pool chemical tracking software runs green-to-clean recoveries: log chlorine, pH, alkalinity, phosphate per pool, schedule rechecks, and bill the work.', href: '/blogs/pool-chemical-tracking-software-green-to-clean-recovery' },
  { title: 'Billing Chemical Upcharges Automatically With Pool Chemical Tracking Software', description: 'See how PoolBossPro turns logged water chemistry into automatic chemical upcharges on the invoice, so every extra dose you pour gets billed and paid.', href: '/blogs/pool-chemical-tracking-software-invoicing-chemical-upcharges' },
  { title: 'How the Job Board Surfaces Chemistry Problems in Pool Chemical Tracking Software', description: 'How the Job Board in pool chemical tracking software flags out-of-range chlorine, pH, and alkalinity readings so problem pools never slip past your route.', href: '/blogs/pool-chemical-tracking-software-job-board-readings' },
  { title: 'Training New Pool Techs Faster With Pool Chemical Tracking Software', description: 'See how PoolBossPro pool chemical tracking software turns new pool techs into confident, route-ready cleaners faster with guided water chemistry logging.', href: '/blogs/pool-chemical-tracking-software-new-technician-training' },
  { title: 'Tracking Phosphates and Algae Triggers With Pool Chemical Tracking Software', description: 'See how PoolBossPro logs phosphate levels by pool, flags algae triggers across your route, and turns green-water risk into scheduled, billable jobs.', href: '/blogs/pool-chemical-tracking-software-phosphate-tracking' },
  { title: 'Pairing Chemical Logs With Photo Proof of Service in Pool Software', description: 'Pool software that pairs water chemistry logs with timestamped service photos gives every pool stop verifiable proof your crew was there and the water was right.', href: '/blogs/pool-chemical-tracking-software-photo-proof-of-service' },
  { title: 'Logging Chemistry for Pool Openings and Closings in Your Software', description: 'Log chemistry for pool openings and closings in your software so every start-up and winterization reading ties to the pool, the invoice, and the customer.', href: '/blogs/pool-chemical-tracking-software-pool-openings-closings' },
  { title: 'Pool Profiles and Equipment Records Inside Pool Chemical Tracking Software', description: 'See how pool profiles and equipment records inside pool chemical tracking software keep crews accurate on water chemistry, dosing, and repairs.', href: '/blogs/pool-chemical-tracking-software-pool-profiles-equipment' },
  { title: 'How Pool Chemical Tracking Software Fits Into Recurring Route Scheduling', description: 'See how PoolBossPro ties water chemistry logging to recurring pool route scheduling so every weekly stop, dose, and invoice stays in one place.', href: '/blogs/pool-chemical-tracking-software-recurring-route-scheduling' },
  { title: 'How Pool Chemical Tracking Software Cuts Cloudy-Water Callbacks', description: 'See how pool chemical tracking software logs water chemistry, surfaces trends, and catches problems early to cut cloudy-water callbacks and free re-visits.', href: '/blogs/pool-chemical-tracking-software-reduce-callbacks' },
  { title: 'Chemical Usage Reporting and Dashboards in Pool Tracking Software', description: 'See how PoolBossPro turns logged water chemistry and chemical doses into reports and dashboards that show usage, cost, and profit per pool and per route.', href: '/blogs/pool-chemical-tracking-software-reporting-dashboards' },
  { title: 'The ROI of Pool Chemical Tracking Software for a Growing Pool Company', description: 'See how pool chemical tracking software pays for itself through faster water testing, fewer callbacks, accurate chemical billing, and tighter routes.', href: '/blogs/pool-chemical-tracking-software-roi-for-pool-companies' },
  { title: 'Logging Salt Pool Readings in Pool Chemical Tracking Software', description: 'How pool chemical tracking software logs salt, chlorine, and stabilizer readings on saltwater pools and ties them to each pool profile and salt cell.', href: '/blogs/pool-chemical-tracking-software-salt-pool-readings' },
  { title: 'Scaling to Multiple Crews With Pool Chemical Tracking Software', description: 'How pool chemical tracking software lets you add a second and third crew without losing route control, water chemistry consistency, or billing accuracy.', href: '/blogs/pool-chemical-tracking-software-scaling-multiple-crews' },
  { title: 'Why Spreadsheets Fail at Pool Chemical Tracking and Software Wins', description: 'Spreadsheets break down once you log chlorine, pH, and alkalinity across dozens of pools. See why pool chemical tracking software wins at scale.', href: '/blogs/pool-chemical-tracking-software-spreadsheets-dont-scale' },
  { title: 'Pool Chemical Tracking Software vs. Paper Test Logs: Why the Clipboard Loses', description: 'See why pool chemical tracking software beats paper test logs for water chemistry history, dosing accuracy, customer proof, and route-ready record keeping.', href: '/blogs/pool-chemical-tracking-software-vs-paper-test-logs' },
  { title: 'Setting Up Pool Chemical Tracking Software in Your First Week', description: 'A practical first-week plan for setting up pool chemical tracking software so chlorine, pH, alkalinity, and salt readings get logged on every stop fast.', href: '/blogs/setting-up-pool-chemical-tracking-software-first-week' },
];

const silo4 = [
  { title: 'From Reading to Dose: Water Balancing Inside Pool Business Software', description: 'How pool business software turns chlorine, pH, and alkalinity readings into accurate dosing recommendations tech crews can trust on every stop.', href: '/blogs/pool-business-software-balancing-readings-dosing' },
  { title: 'Tracking Chemical Inventory and Costs in Pool Business Software', description: 'How PoolBossPro tracks chemical inventory and per-pool costs from the water-chemistry log so you reorder on time and price routes for real profit.', href: '/blogs/pool-business-software-chemical-inventory-costs' },
  { title: 'How to Choose the Right Pool Business Software: A Buyer\'s Checklist', description: 'A practical buyer\'s checklist for choosing pool business software: recurring routes, dispatch, water chemistry logging, card-on-file billing, and reporting.', href: '/blogs/pool-business-software-choosing-the-right-platform' },
  { title: 'Managing Commercial Pool Accounts With Pool Business Software', description: 'See how PoolBossPro manages commercial pool accounts with recurring routes, water chemistry logs, crew dispatch, and card-on-file invoicing.', href: '/blogs/pool-business-software-commercial-accounts' },
  { title: 'Pool Business Software: The Complete Guide for Pool Service Owners', description: 'How pool business software runs recurring routes, crew dispatch, water chemistry logging, card-on-file billing, and customer texts for pool service owners.', href: '/blogs/pool-business-software-complete-guide' },
  { title: 'Crew Dispatch and Routing in Pool Business Software', description: 'How pool business software dispatches recurring routes, pool profiles, water chemistry forms, and stop order to cleaning crews from one office action.', href: '/blogs/pool-business-software-crew-dispatch-routing' },
  { title: 'How Pool Business Software Improves the Customer Experience', description: 'See how PoolBossPro improves the customer experience with on-time pool visits, water chemistry logs, automatic texts, and easy card-on-file billing.', href: '/blogs/pool-business-software-customer-experience' },
  { title: 'Customer Texts in Pool Business Software: On-My-Way and Service Updates', description: 'How PoolBossPro fires on-my-way and service-update texts off your recurring pool routes, so customers stay informed and stop calling to ask if you came.', href: '/blogs/pool-business-software-customer-text-notifications' },
  { title: 'Tracking Cyanuric Acid, Salt, and Phosphates in Pool Business Software', description: 'How PoolBossPro logs cyanuric acid, salt, and phosphate readings on every pool stop so your crews dose right and your route stays profitable.', href: '/blogs/pool-business-software-cyanuric-salt-phosphate-tracking' },
  { title: 'Managing Equipment Repair Jobs With Pool Business Software', description: 'How pool business software turns equipment repair calls into scheduled, profitable jobs with dispatch, parts tracking, invoicing, and card-on-file payment.', href: '/blogs/pool-business-software-equipment-repair-jobs' },
  { title: 'Setting Up Pool Business Software: A Step-by-Step First-Week Plan', description: 'A practical first-week setup plan for pool service software: load pool profiles, build recurring routes, log water chemistry, and turn on card-on-file invoicing.', href: '/blogs/pool-business-software-getting-started-setup' },
  { title: 'Running Green-to-Clean Recovery Jobs in Pool Business Software', description: 'How pool business software runs green-to-clean recovery jobs &mdash; scheduling, chemistry logging, multi-visit tracking, and billing &mdash; so swampy pools turn a profit.', href: '/blogs/pool-business-software-green-to-clean-recovery' },
  { title: 'Pool Business Software Setup: Importing Customers and Building Pool Profiles', description: 'How to import your pool service customers and build complete pool profiles in PoolBossPro so routing, water chemistry logging, and billing work from day one.', href: '/blogs/pool-business-software-import-customers-pool-profiles' },
  { title: 'Invoicing and Card-on-File Payments in Pool Business Software', description: 'How pool business software invoices weekly cleaning routes and charges cards on file automatically so you get paid the day service is done.', href: '/blogs/pool-business-software-invoicing-card-on-file' },
  { title: 'The Job Board in Pool Business Software: Every Pool Visit at a Glance', description: 'How the Job Board in pool business software shows every pool visit, water test, and repair due today so you can dispatch crews and never miss a stop.', href: '/blogs/pool-business-software-job-board-explained' },
  { title: 'The KPIs That Matter: Profit per Stop in Pool Business Software', description: 'How PoolBossPro tracks profit per stop, route revenue, and the pool service KPIs that tell you which weekly cleaning accounts actually make money.', href: '/blogs/pool-business-software-kpis-profit-per-stop' },
  { title: 'Onboarding New Pool Techs Fast With Pool Business Software', description: 'See how PoolBossPro turns ramp-up into routine: route profiles, water chemistry logging, and dispatch get new pool techs productive in days, not weeks.', href: '/blogs/pool-business-software-onboarding-new-technicians' },
  { title: 'Pool Openings and Closings: Scheduling Seasonal Work in Pool Business Software', description: 'How PoolBossPro schedules seasonal pool openings and closings — batch jobs onto the board, route crews, log water chemistry, and invoice with card on file.', href: '/blogs/pool-business-software-openings-closings' },
  { title: 'Photo Documentation at the Pool With Pool Business Software', description: 'How pool business software lets techs snap before-and-after pool photos in the field, attach them to the visit, and send proof to customers automatically.', href: '/blogs/pool-business-software-photo-documentation' },
  { title: 'Pool and Property Profiles in Pool Business Software: Size, Gallons, Equipment', description: 'How pool and property profiles in pool business software store size, gallons, and equipment so your crews dose chemicals and service pools correctly every visit.', href: '/blogs/pool-business-software-pool-property-profiles' },
  { title: 'Recurring Billing and Autopay With Pool Business Software', description: 'How recurring billing and autopay in pool business software charge weekly cleaning customers automatically, end accounts receivable, and stabilize cash flow.', href: '/blogs/pool-business-software-recurring-billing-autopay' },
  { title: 'How Pool Business Software Builds Recurring Weekly Cleaning Routes', description: 'See how pool business software builds recurring weekly cleaning routes, auto-fills the Job Board, dispatches crews, and logs water chemistry on every stop.', href: '/blogs/pool-business-software-recurring-route-scheduling' },
  { title: 'Reducing Skipped Stops and No-Shows With Pool Business Software', description: 'How pool business software cuts skipped stops and no-shows with recurring routes, dispatch visibility, customer texts, and completion logging on every pool.', href: '/blogs/pool-business-software-reducing-skipped-stops' },
  { title: 'Reporting and Dashboards: Seeing Your Pool Business Clearly', description: 'How pool service software turns routes, water chemistry, invoices, and texts into dashboards and reports that show exactly how your pool business is performing.', href: '/blogs/pool-business-software-reporting-dashboards' },
  { title: 'The ROI of Pool Business Software: What It Pays Back Every Month', description: 'Where pool business software earns its keep every month: tighter routes, captured upcharges, faster card-on-file payments, fewer missed stops, and saved office hours.', href: '/blogs/pool-business-software-roi-payback' },
  { title: 'Pool Business Software and Route Density: Cleaning More Pools per Mile', description: 'See how pool business software tightens routes, raises pool density per stop, and cuts drive time so your crews clean more pools per mile each week.', href: '/blogs/pool-business-software-route-density-fewer-miles' },
  { title: 'Scaling From One Truck to Multiple Crews With Pool Business Software', description: 'How pool business software lets you split recurring routes, dispatch multiple crews, and track water chemistry and payments across every truck from one screen.', href: '/blogs/pool-business-software-scaling-multiple-crews' },
  { title: 'After-Visit Service Reports Customers Love, Sent by Pool Business Software', description: 'How pool business software builds and sends an after-visit service report with water chemistry readings, chemicals added, and photos right after each stop.', href: '/blogs/pool-business-software-service-reports-after-visit' },
  { title: 'Pool Business Software vs. Spreadsheets and Paper Route Sheets', description: 'Why pool business software beats spreadsheets and paper route sheets: recurring routes, water chemistry history, dispatch, and automatic card-on-file billing.', href: '/blogs/pool-business-software-vs-spreadsheets-paper' },
  { title: 'Logging Water Chemistry in Pool Business Software: Chlorine, pH, and More', description: 'How PoolBossPro logs chlorine, pH, alkalinity, cyanuric, salt, and phosphate readings on every pool stop and turns them into dosing, billing, and reports.', href: '/blogs/pool-business-software-water-chemistry-logging' },
];

const silo5 = [
  { title: 'Adding Pool Equipment Repair as a Second Revenue Stream in Software', description: 'How PoolBossPro lets pool cleaning companies add equipment repair as a second revenue stream, capturing repairs at the stop and billing them on the card on file.', href: '/blogs/add-pool-equipment-repairs-revenue-stream' },
  { title: 'Automating Customer Texts for Weekly Pool Cleaning Visits', description: 'How PoolBossPro auto-sends customer texts for weekly pool cleaning visits, so every stop, water reading, and reschedule reaches the homeowner without you typing.', href: '/blogs/automate-pool-cleaning-customer-texts' },
  { title: 'Best Pool Service Software vs. Generic Scheduling Tools', description: 'See why pool service software beats generic scheduling apps: route-based recurring stops, water chemistry logging, dispatch, and card-on-file billing.', href: '/blogs/best-pool-service-software-vs-generic' },
  { title: 'Build Tighter Pool Service Routes by Route Density, Not Guesswork', description: 'How PoolBossPro builds pool service routes by route density from a map so weekly cleaning crews drive less, hit more stops, and stay on schedule.', href: '/blogs/build-pool-service-routes-by-density' },
  { title: 'Keeping Chemical Dosing Records Customers Actually Trust', description: 'How PoolBossPro logs every chlorine, pH, and chemical dose at the pool so the records you hand customers are accurate, consistent, and trusted.', href: '/blogs/chemical-dosing-records-pool-customers' },
  { title: 'Logging Chlorine, pH, and Alkalinity on Every Pool the Same Way', description: 'How pool maintenance software gives every tech the same structured chemistry form so chlorine, pH, and alkalinity get logged consistently on every pool stop.', href: '/blogs/chlorine-ph-alkalinity-logging-software' },
  { title: 'How to Dispatch Pool Cleaning Crews Without a Single Phone Call', description: 'How digital dispatch in pool maintenance software sends recurring routes, pool profiles, and water chemistry forms to crews without a single phone call.', href: '/blogs/dispatch-pool-cleaning-crews-software' },
  { title: 'Tracking Green-to-Clean Pool Recovery Jobs in Your Software', description: 'See how PoolBossPro tracks green-to-clean pool recovery jobs with water chemistry logs, multi-visit scheduling, photo updates, and card-on-file invoicing.', href: '/blogs/green-to-clean-recovery-pool-software' },
  { title: 'Growing a Pool Service Business From 50 to 300 Accounts With Software', description: 'Grow a pool service company from 50 to 300 accounts using PoolBossPro recurring route scheduling, crew dispatch, water chemistry logging, and card-on-file billing.', href: '/blogs/grow-pool-service-business-50-to-300' },
  { title: 'How to Spot and Handle Overdue Pool Cleaning Visits', description: 'How PoolBossPro flags overdue pool cleaning visits in your route schedule so you can dispatch crews, text customers, and protect recurring accounts.', href: '/blogs/handle-overdue-pool-cleaning-visits' },
  { title: 'How to Invoice Recurring Pool Cleaning Accounts Automatically', description: 'How PoolBossPro auto-generates recurring pool cleaning invoices and charges card-on-file customers so weekly route revenue lands on time, no chasing.', href: '/blogs/invoice-recurring-pool-cleaning-automatically' },
  { title: 'Know Your Pool Route Revenue Before the Truck Leaves', description: 'See the dollar value of every pool route before dispatch with PoolBossPro &mdash; total Job Board revenue, selected-route totals, and per-service breakdowns every morning.', href: '/blogs/know-pool-route-revenue-before-dispatch' },
  { title: 'Logging Water Chemistry on Every Pool Stop With Maintenance Software', description: 'Log chlorine, pH, alkalinity, cyanuric, salt and phosphate on every pool stop with PoolBossPro so every reading is timestamped and saved to the profile.', href: '/blogs/log-water-chemistry-pool-maintenance-software' },
  { title: 'Tracking Pool Equipment Repairs Alongside Weekly Maintenance', description: 'How PoolBossPro tracks pump, filter, and heater repairs right alongside weekly cleaning and water chemistry logs so nothing falls through the cracks.', href: '/blogs/pool-equipment-repair-tracking-software' },
  { title: 'Pool Maintenance Software vs. Spreadsheets for Water Chemistry', description: 'See why pool maintenance software beats spreadsheets for logging chlorine, pH, alkalinity, and salt readings on every recurring pool cleaning stop.', href: '/blogs/pool-maintenance-software-vs-spreadsheets' },
  { title: 'Why Pool Property Profiles &mdash; Gallons, Type, and Equipment &mdash; Belong in Your Software', description: 'Pool property profiles in PoolBossPro store gallons, pool type, and equipment so dosing, dispatch, and repairs are accurate on every recurring stop.', href: '/blogs/pool-property-profiles-gallons-equipment' },
  { title: 'Knowing Which Pool Service Customers Are Up for Renewal', description: 'See how PoolBossPro flags which pool service customers are up for renewal so you can re-sign seasonal accounts before they lapse and revenue slips.', href: '/blogs/pool-service-customer-renewal-tracking' },
  { title: 'Using the Job Board to Catch Pool Repairs and Overflow Work', description: 'See how PoolBossPro&apos;s Job Board captures pool repairs, green-to-clean jobs, and overflow stops so nothing slips between your recurring routes.', href: '/blogs/pool-service-job-board-overflow-work' },
  { title: 'How Pool Service Software Handles Cleaning, Chemistry, and Repairs in One Account', description: 'See how PoolBossPro runs recurring cleaning routes, water chemistry logs, and equipment repairs from one account with shared pool profiles and billing.', href: '/blogs/pool-service-software-multiple-service-types' },
  { title: 'Sending Water Chemistry Reports That Win Pool Customers Over', description: 'How pool service software turns every chlorine, pH, and alkalinity reading into a customer-facing water chemistry report that builds trust and reduces churn.', href: '/blogs/pool-service-water-chemistry-reports-customers' },
  { title: 'What Your Pool Technician Sees: Route, Property Notes, and Chemistry Form', description: 'A walkthrough of the PoolBossPro mobile tech view: the day&apos;s route, pool property notes, and the water chemistry form techs fill out at every stop.', href: '/blogs/pool-technician-mobile-route-chemistry-form' },
  { title: 'Pricing Recurring Pool Service by Gallons and Pool Type', description: 'PoolBossPro stores gallons, pool type, and equipment on each profile so you can price recurring pool service by real workload and chemical cost, not guesswork.', href: '/blogs/price-recurring-pool-service-by-gallons' },
  { title: 'Cutting Windshield Time Between Pool Stops With Smart Routing', description: 'How PoolBossPro smart routing sequences recurring pool stops to cut windshield time, lower fuel cost, and fit more weekly pools into every route day.', href: '/blogs/reduce-pool-service-windshield-time' },
  { title: 'The ROI of Pool Maintenance Software in Saved Office Hours', description: 'How pool maintenance software pays for itself by cutting weekly route scheduling, chemistry logging, invoicing, and customer text overhead down to minutes.', href: '/blogs/roi-pool-maintenance-software-office-hours' },
  { title: 'Running a Pool Service Business Without a Full-Time Office Manager', description: 'Run a pool service business without an office manager using PoolBossPro for recurring route scheduling, dispatch, water chemistry logging, and card-on-file billing.', href: '/blogs/run-pool-business-without-office-manager' },
  { title: 'Keeping Salt, Cyanuric Acid, and Phosphate Readings With Pool History', description: 'See how PoolBossPro stores salt, cyanuric acid, and phosphate readings inside each pool history so techs catch slow-moving trends before a pool goes green.', href: '/blogs/salt-cyanuric-phosphate-readings-history' },
  { title: 'Scheduling Pool Openings and Closings Without the Spring Scramble', description: 'PoolBossPro software lets you batch-schedule every pool opening and closing, dispatch crews by route, and bill on file so spring never turns into a scramble.', href: '/blogs/schedule-pool-openings-closings-software' },
  { title: 'How to Set Up Recurring Weekly Pool Cleaning Routes in PoolBossPro', description: 'A step-by-step guide to building recurring weekly pool cleaning routes in PoolBossPro so visits auto-generate, crews stay routed, and nothing slips.', href: '/blogs/set-up-recurring-pool-cleaning-routes' },
  { title: 'What Pool Maintenance Software Actually Does for a Pool Service Business', description: 'Pool maintenance software runs recurring cleaning routes, logs water chemistry, dispatches crews, and bills card-on-file payments&mdash;here is what it does day to day.', href: '/blogs/what-is-pool-maintenance-software' },
];

const silo6 = [
  { title: 'How to Send Automatic Customer Texts for Every Pool Service Visit', description: 'Set up automatic customer texts in PoolBossPro so every pool service visit triggers an on-my-way, completed, and water-chemistry update with no extra effort.', href: '/blogs/automatic-customer-texts-pool-service-visits' },
  { title: 'How to Build a Full Day of Pool Routes in Under 30 Minutes Every Morning', description: 'How pool route software builds a full day of recurring stops, dispatches crews with pool profiles and chemistry forms, and gets trucks rolling in under 30 minutes.', href: '/blogs/build-pool-routes-fast-every-morning' },
  { title: 'How to Dispatch Pool Cleaning Crews Without Calling or Texting Them Every Morning', description: 'Stop the morning dispatch call. See how pool service software pushes each crew a complete, mapped route with pool profiles, chemistry forms, and live status.', href: '/blogs/dispatch-pool-cleaning-crews-mobile' },
  { title: 'How to Handle Overdue and Skipped Pool Stops Before Customers Notice', description: 'Use PoolBossPro route &amp; dispatch software to catch overdue and skipped pool stops, reschedule fast, and text customers before they ever notice a missed visit.', href: '/blogs/handle-overdue-skipped-pool-stops' },
  { title: 'How to Invoice Per Pool Stop and Get Paid the Day Service Is Done', description: 'See how pool route software invoices each pool stop the moment it&apos;s completed and charges the card on file, so your whole route gets paid the same day.', href: '/blogs/invoice-per-pool-stop-card-on-file-payments' },
  { title: 'How to Log Water Chemistry on Every Pool Stop From the Tech&apos;s Phone', description: 'How pool service software puts a per-pool chemistry form on the tech&apos;s phone so chlorine, pH, alkalinity, and salt readings get logged on every stop.', href: '/blogs/log-water-chemistry-every-pool-stop' },
  { title: 'How to Manage Multiple Pool Crews and Routes From One Dispatch Screen', description: 'Run multiple pool service crews from a single dispatch screen: split recurring routes, assign stops, track water chemistry, and monitor every tech in real time.', href: '/blogs/manage-multiple-pool-crews-routes' },
  { title: 'How to Manage Pool Openings and Closings Alongside Weekly Cleaning Routes', description: 'Run seasonal pool openings and closings without breaking weekly cleaning routes&mdash;use PoolBossPro to dispatch, schedule, log chemistry, and invoice in one place.', href: '/blogs/manage-pool-openings-closings-route-software' },
  { title: 'Manual Pool Dispatch vs. Software: A Side-by-Side Look at a Monday Morning', description: 'See how PoolBossPro dispatch software beats whiteboards and group texts for routing weekly pool cleaning crews, logging water chemistry, and billing.', href: '/blogs/manual-pool-dispatch-vs-software' },
  { title: 'Pool &amp; Property Profiles: Storing Pool Type, Gallons, and Equipment for Every Stop', description: 'How PoolBossPro stores pool type, gallons, and equipment in property profiles so every tech arrives at each stop already knowing the pool.', href: '/blogs/pool-property-profiles-route-software' },
  { title: 'What Route Density Means for a Pool Service Business and How Software Builds It', description: 'What route density means for a pool service business and how pool route software builds it with map-based scheduling, dispatch, chemistry logging, and reporting.', href: '/blogs/pool-route-density-software' },
  { title: 'Pool Route & Dispatch Software: The Complete Guide for Pool Service Businesses', description: 'How pool route and dispatch software runs recurring cleaning routes, logs water chemistry, dispatches crews, and bills card-on-file for pool service businesses.', href: '/blogs/pool-route-dispatch-software-complete-guide' },
  { title: 'The ROI of Pool Route &amp; Dispatch Software in Your First 90 Days', description: 'A 90-day look at how pool route and dispatch software pays for itself: tighter routes, on-time recurring billing, fewer missed stops, and card-on-file payments.', href: '/blogs/pool-route-dispatch-software-roi-90-days' },
  { title: 'Pool Route Optimization: How to Cut Windshield Time and Fit More Pools Per Day', description: 'How PoolBossPro optimizes pool service route order to cut windshield time, lower fuel costs, and fit more weekly pool stops into every route day.', href: '/blogs/pool-route-optimization-fewer-miles-more-stops' },
  { title: 'Pool Route Reporting: The Numbers Owners Should Check Every Week', description: 'How PoolBossPro reporting surfaces the weekly pool route numbers owners should check: route revenue, completed stops, chemistry exceptions, overdue accounts, and payments.', href: '/blogs/pool-route-reporting-weekly-numbers' },
  { title: 'Pool Route Software vs. Generic Field Service Software: What Actually Differs', description: 'The specific features that separate purpose-built pool route software from generic field service tools: recurring routes, water chemistry logs, and dispatch.', href: '/blogs/pool-route-software-vs-generic-field-service' },
  { title: 'Pool Route Software vs. Spreadsheets: Where Spreadsheets Break After 100 Pools', description: 'See exactly where a pool service spreadsheet breaks down past 100 pools, and which route, water chemistry, and billing tasks purpose-built software handles for you.', href: '/blogs/pool-route-software-vs-spreadsheets' },
  { title: 'How the Job Board Works: Assigning Pool Stops to the Right Tech in Seconds', description: 'See how the PoolBossPro Job Board lets you assign weekly pool cleaning stops to the right tech in seconds with drag-and-drop routing and dispatch.', href: '/blogs/pool-service-job-board-crew-assignment' },
  { title: 'Pool Service Verification: Proving Every Stop Was Completed With Photos and Readings', description: 'How PoolBossPro proves every weekly pool stop was completed with timestamped photos, water chemistry readings, and customer texts you can pull up in seconds.', href: '/blogs/pool-service-verification-photos-readings' },
  { title: 'How to Bill Recurring Pool Cleaning Monthly With Card on File', description: 'Bill recurring weekly pool cleaning as a flat monthly charge with card on file in PoolBossPro so payments run on autopilot and cash flow stays steady.', href: '/blogs/recurring-pool-cleaning-billing-card-on-file' },
  { title: 'How to Reorder Pool Stops on the Fly When a Tech Calls in Sick', description: 'When a pool tech calls in sick, PoolBossPro lets you reassign routes, reorder stops, and text customers in minutes so no weekly cleaning gets skipped.', href: '/blogs/reorder-pool-stops-reassign-routes' },
  { title: 'How to Route and Track Pool Equipment Repair Calls Between Cleaning Stops', description: 'Use PoolBossPro to slot pool equipment repair calls into existing cleaning routes, dispatch the right tech, and track parts, photos, and invoices.', href: '/blogs/route-pool-equipment-repair-calls' },
  { title: 'How to Scale a Pool Service Business From 100 to 1,000 Stops Without an Office Manager', description: 'Scale a pool service company to 1,000 weekly stops without hiring an office manager using PoolBossPro route-based scheduling, dispatch, and automated billing.', href: '/blogs/scale-pool-service-business-without-office-manager' },
  { title: 'How to Schedule and Dispatch a Green-to-Clean Recovery as a Multi-Visit Job', description: 'How pool route software schedules a green-to-clean as a multi-visit job, dispatches the return trips, and logs water chemistry on every pass.', href: '/blogs/schedule-green-to-clean-recovery-dispatch' },
  { title: 'How to Set Up Recurring Weekly Pool Cleaning Routes That Schedule Themselves', description: 'Set up recurring weekly pool cleaning routes in PoolBossPro so stops auto-reschedule, crews get dispatched, and your week builds itself without manual booking.', href: '/blogs/set-up-recurring-weekly-pool-cleaning-routes' },
  { title: 'How to Track Salt and Phosphate Readings Across Every Pool on the Route', description: 'How PoolBossPro logs salt and phosphate readings at every pool stop, ties them to property profiles, and flags trends before they turn into algae or salt-cell problems.', href: '/blogs/track-salt-phosphate-readings-pool-route' },
  { title: 'Chlorine, pH, Alkalinity, and CYA: Building a Water Chemistry Log Your Techs Actually Use', description: 'How pool route software turns chlorine, pH, alkalinity, and CYA readings into a per-pool chemistry log techs actually fill out and the office can trust.', href: '/blogs/water-chemistry-logging-pool-route-software' },
  { title: 'What Pool Service Customers Expect Before, During, and After Every Visit', description: 'How pool service software meets customer expectations before, during, and after each visit with reminders, chemistry logging, automatic texts, and card-on-file billing.', href: '/blogs/what-pool-customers-expect-every-visit' },
  { title: 'What to Look for in Pool Route &amp; Dispatch Software Before You Buy', description: 'A practical checklist for buying pool route and dispatch software: recurring scheduling, map routing, water chemistry logging, card-on-file billing, and reporting.', href: '/blogs/what-to-look-for-pool-route-dispatch-software' },
];

const silo7 = [
  { title: 'Add Chemicals to Pool Invoices Automatically From the Water-Chemistry Log', description: 'How PoolBossPro turns the water-chemistry readings your techs log on every pool stop into line-item chemical charges on the invoice automatically.', href: '/blogs/add-chemicals-to-pool-invoices-automatically' },
  { title: 'Auto-Invoice Every Weekly Pool Route Without Touching a Calculator', description: 'PoolBossPro auto-invoices every weekly pool route the moment a clean is logged, so recurring billing runs itself and no chemicals or stops slip.', href: '/blogs/auto-invoice-weekly-pool-routes' },
  { title: 'How to Bill Green-to-Clean Recovery Jobs So You Never Lose Money', description: 'Use PoolBossPro to scope, document, and invoice green-to-clean pool recovery jobs with phased line items and card-on-file payment so you never eat the cost.', href: '/blogs/bill-green-to-clean-recovery-jobs' },
  { title: 'Build a Pool Service Price Book So Every Tech Bills the Same', description: 'Build a standardized price book in PoolBossPro so every tech bills the same flat rates, per-visit jobs, and chemical upcharges off your recurring pool route.', href: '/blogs/build-pool-service-price-book' },
  { title: 'Card-on-File Payments for Pool Service: Get Paid the Day You Clean', description: 'How card-on-file charging in PoolBossPro collects payment the day you clean each pool, ending invoices, statements, and chasing down late checks.', href: '/blogs/card-on-file-payments-pool-service' },
  { title: 'Charge for Extra Pool Visits Without the End-of-Month Argument', description: 'Use PoolBossPro to document and invoice extra pool visits the moment they happen, so customers see proof and pay without the end-of-month billing argument.', href: '/blogs/charge-extra-pool-visits-without-arguments' },
  { title: 'Flat-Rate vs. Per-Visit Pool Billing: How PoolBossPro Handles Both', description: 'See how PoolBossPro runs flat-rate monthly plans and per-visit pool billing side by side, charging the right card-on-file amount off your recurring route automatically.', href: '/blogs/flat-rate-vs-per-visit-pool-billing' },
  { title: 'Invoice Pool Equipment Repairs On-Site Before the Crew Leaves', description: 'Invoice pool equipment repairs on-site with PoolBossPro&mdash;build the bill at the pad, charge card-on-file, and collect before the crew drives away.', href: '/blogs/invoice-pool-equipment-repairs-on-site' },
  { title: 'Monthly Pool Billing vs. Per-Clean Charges: Smoothing Cash Flow', description: 'See how PoolBossPro flat monthly pool billing and card-on-file payments smooth cash flow versus per-clean charges for recurring pool service routes.', href: '/blogs/monthly-pool-billing-vs-per-clean' },
  { title: 'Find Your Most Profitable Pools Using Billing and Route Data', description: 'Use PoolBossPro billing and route data to rank pools by profit per stop &mdash; combine invoice totals, pool profiles, chemistry, and route density to find your best accounts.', href: '/blogs/per-pool-profitability-billing-data' },
  { title: 'Pricing and Billing Pool Service by Pool Type, Size, and Gallons', description: 'Use PoolBossPro pool profiles to price and bill weekly cleaning by pool type, size, and gallons so every invoice matches the real work.', href: '/blogs/pool-billing-by-pool-size-gallons' },
  { title: 'Invoicing Pool Openings and Closings as Seasonal One-Off Jobs', description: 'How PoolBossPro lets pool service pros invoice seasonal pool openings and closings as one-off jobs with card-on-file payments and clean records.', href: '/blogs/pool-opening-closing-invoicing' },
  { title: 'Read Your Pool Route Revenue Before You Dispatch a Single Crew', description: 'PoolBossPro shows you committed revenue, route value, and unbilled stops before any crew rolls out, so you dispatch pool routes with the numbers in front of you.', href: '/blogs/pool-route-revenue-reporting' },
  { title: 'How Pool Service Billing Software Cuts 10 Office Hours a Week', description: 'See how PoolBossPro billing software auto-builds pool service invoices from completed stops, charges cards on file, and chases overdue accounts for you.', href: '/blogs/pool-service-billing-cuts-office-hours' },
  { title: 'The ROI of Pool Service Billing Software: One Crew Pays for the Year', description: 'How pool service billing software pays for itself: faster card-on-file payments, fewer missed charges on weekly routes, and far less time chasing checks.', href: '/blogs/pool-service-billing-roi' },
  { title: 'Give Pool Customers a Self-Serve Billing Portal That Pays You Faster', description: 'A self-serve pool billing portal lets customers view invoices, pay by card, and update cards on file 24/7 — so you get paid faster with no phone tag.', href: '/blogs/pool-service-customer-billing-portal' },
  { title: 'Collecting Deposits on Big Pool Repair Jobs Before Work Starts', description: 'See how PoolBossPro lets pool service pros invoice a deposit, take a card-on-file payment, and lock in big repair jobs before any work begins.', href: '/blogs/pool-service-deposits-repair-jobs' },
  { title: 'Failed Card? How PoolBossPro Recovers Pool Service Payments Automatically', description: 'See how PoolBossPro retries failed pool service cards, texts customers to update payment, and recovers recurring revenue automatically without chasing checks.', href: '/blogs/pool-service-failed-payment-recovery' },
  { title: 'Send Pool Service Invoices From the Truck Between Stops', description: 'See how PoolBossPro lets pool techs invoice from the truck between stops and charge the card on file, so your route bills itself the same day.', href: '/blogs/pool-service-invoices-from-the-truck' },
  { title: 'Pool Service Invoicing Software vs. Spreadsheets: Why Pool Pros Make the Switch', description: 'Why pool pros drop spreadsheets for invoicing software that bills recurring stops automatically, charges cards on file, and ties billing to the route.', href: '/blogs/pool-service-invoicing-software-vs-spreadsheets' },
  { title: 'The Payment Options Pool Customers Actually Want in 2026', description: 'How card-on-file, automatic per-visit charging, and text-based receipts in PoolBossPro give pool service customers the payment options they actually prefer.', href: '/blogs/pool-service-payment-options-customers-want' },
  { title: 'Pool Service Tax Season Made Easy With Clean Billing Records', description: 'How clean, software-kept pool service billing records make tax season fast: every invoice, card-on-file payment, and route logged and exportable in minutes.', href: '/blogs/pool-service-tax-season-records' },
  { title: 'Prorate Mid-Month Pool Customers Without the Math Headache', description: 'PoolBossPro prorates mid-month pool service customers automatically so partial-month invoices are accurate, fair, and ready to charge card-on-file in seconds.', href: '/blogs/prorate-mid-month-pool-customers' },
  { title: 'Reconcile Pool Service Payments Fast With Built-In Reporting', description: 'PoolBossPro reporting reconciles pool service payments fast: match invoices, card-on-file charges, and deposits to deposits in your bank in minutes.', href: '/blogs/reconcile-pool-service-payments-fast' },
  { title: 'Reduce Pool Service Billing Errors With Job-Linked Invoicing', description: 'How PoolBossPro ties every invoice to the completed pool stop and its water chemistry log so you bill the right amount, every time, without re-keying numbers.', href: '/blogs/reduce-pool-service-billing-errors' },
  { title: 'How Frictionless Billing Reduces Pool Service Customer Churn', description: 'How card-on-file billing, automatic receipts, and clean invoicing in PoolBossPro keep recurring pool cleaning customers from canceling over payment friction.', href: '/blogs/reduce-pool-service-churn-with-billing' },
  { title: 'Scaling Pool Service Billing Across Multiple Crews and Routes', description: 'PoolBossPro scales pool service billing across every crew and route, auto-invoicing each completed clean so multi-truck billing stays accurate and on time.', href: '/blogs/scale-pool-billing-multiple-crews' },
  { title: 'How to Set Up Recurring Pool Cleaning Billing in PoolBossPro', description: 'Set up recurring weekly pool cleaning billing in PoolBossPro with card-on-file payments, route-based scheduling, and automatic invoices that bill themselves.', href: '/blogs/set-up-recurring-pool-cleaning-billing' },
  { title: 'Stop Chasing Late Pool Service Payments: Automated Reminders That Work', description: 'Set up automated invoice reminders in PoolBossPro so late pool service payments collect themselves instead of forcing you to make awkward collection calls.', href: '/blogs/stop-chasing-late-pool-service-payments' },
  { title: 'Text Pool Customers a Paid Receipt the Moment the Charge Clears', description: 'How PoolBossPro texts pool service customers an instant paid receipt the second the card-on-file charge clears, ending billing confusion and disputes.', href: '/blogs/text-pool-customers-paid-receipts' },
];

export default function BlogIndexPage() {
  return (
    <BlogShell>
      <div className="blog-index">
        <h1>Pool Service Software Blog</h1>
        <p className="blog-index-sub">Guides on scheduling, routes, water chemistry, cleaning, maintenance, invoicing, and growing a pool service business.</p>

        <h2 className="blog-index-silo-title">Pool Service Software</h2>
        <div className="blog-index-grid">
          {silo0.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Pool Scheduling Software</h2>
        <div className="blog-index-grid">
          {silo1.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Pool Cleaning Software</h2>
        <div className="blog-index-grid">
          {silo2.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Pool Chemical Tracking Software</h2>
        <div className="blog-index-grid">
          {silo3.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Pool Business Software</h2>
        <div className="blog-index-grid">
          {silo4.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Pool Maintenance Software</h2>
        <div className="blog-index-grid">
          {silo5.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Pool Route &amp; Dispatch Software</h2>
        <div className="blog-index-grid">
          {silo6.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Pool Invoicing &amp; Billing</h2>
        <div className="blog-index-grid">
          {silo7.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>
      </div>
    </BlogShell>
  );
}
